apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miracle6-data
  namespace: miracle6
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
