apiVersion: v1
kind: Namespace
metadata:
  name: miracle6
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before other resources
  labels:
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before other resources
  labels:
    environment: prod
---